### ISSUE TITLE
 jump to the wrong page when click the search result

### ISSUE THREAD

**Issue by wenhaiz** [ShikherVerma/Shikherverma.github.io#2]
hi，I'm an Android developer from China.
I really like your template and I forked it and begin to customize it.
I just found out that when I click the post listed in the search page,it jump to the search page again rather than content of the post I just clicked. 
I thought I did something stupid at first but when I do this on your blog,it happens again.
I'm not familiar with jekyll ,so I hope you can fix this.
Thanks for the template again.

**Comment by ShikherVerma** [comment]
Thanks for reporting this @wenhaiz :+1: 
Fixed it in the [latest commit](https://github.com/ShikherVerma/Shikherverma.github.io/commit/17c5864c3915a722d302a84aa1fa94cac23736e8).

**Comment by wenhaiz** [comment]
Thanks. @ShikherVerma
